/* Click/tap + keyboard behavior for KB reference popovers.
   Auto-generated by build_growdaily.py. CSS :hover/:focus-within already covers
   mouse and keyboard; this adds tap-to-toggle on touch and Esc/outside-click to
   close. */
(function () {
  function closeAll(except) {
    document.querySelectorAll('.kb-ref.kb-open').forEach(function (el) {
      if (el !== except) el.classList.remove('kb-open');
    });
  }
  function toggle(ref) {
    var open = ref.classList.contains('kb-open');
    closeAll(ref);
    ref.classList.toggle('kb-open', !open);
  }
  document.addEventListener('click', function (e) {
    var ref = e.target.closest ? e.target.closest('.kb-ref') : null;
    if (ref) { e.preventDefault(); toggle(ref); }
    else { closeAll(null); }
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { closeAll(null); return; }
    var active = document.activeElement;
    if ((e.key === 'Enter' || e.key === ' ') && active && active.classList &&
        active.classList.contains('kb-ref')) {
      e.preventDefault();
      toggle(active);
    }
  });
})();
