/* Fullscreen slideshow lightbox for report images.
   Auto-generated by build_growdaily.py — edit the constant there, not here.
   Collects every content image on the page (full-res target = the wrapping
   <a>'s href when it points at an image, else the img src), opens on click,
   and navigates by swipe/drag, arrow keys, or buttons. The bottom bar shows
   the figure caption (bold lead = title, status pill = badge) and position. */
(function () {
  var IMG_RE = /\.(jpe?g|png|gif|webp|avif)(\?.*)?$/i;

  function collect() {
    var slides = [];
    document.querySelectorAll('img').forEach(function (img) {
      if (img.closest('#gb-lb')) return;
      var a = img.closest('a');
      var href = a && a.getAttribute('href');
      var src = href && IMG_RE.test(href) ? href : img.getAttribute('src');
      if (!src || !IMG_RE.test(src)) return;
      var title = '', desc = '', status = '', warn = false;
      var fig = img.closest('figure');
      var cap = fig && fig.querySelector('figcaption');
      if (cap) {
        var c = cap.cloneNode(true);
        var lead = c.querySelector('b, strong');
        if (lead) { title = lead.textContent.trim(); lead.remove(); }
        var pill = c.querySelector('.pill, .badge');
        if (pill) {
          status = pill.textContent.trim();
          warn = /warn|attention/i.test(pill.className + ' ' + status);
          pill.remove();
        }
        desc = c.textContent.replace(/\s+/g, ' ').trim()
          .replace(/^[\u2014\u2013\u00b7:,\-\s]+/, '');
      }
      if (!title) title = (img.getAttribute('alt') || '').trim();
      if (!title) title = decodeURIComponent(src.split('/').pop());
      slides.push({ el: img, src: src, title: title, desc: desc,
                    status: status, warn: warn });
    });
    return slides;
  }

  function el(tag, cls, html) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html != null) e.innerHTML = html;
    return e;
  }

  var slides = collect();
  if (!slides.length) return;

  var root = el('div');
  root.id = 'gb-lb';
  root.hidden = true;
  root.setAttribute('role', 'dialog');
  root.setAttribute('aria-modal', 'true');
  root.setAttribute('aria-label', 'Image viewer');
  if (slides.length < 2) root.className = 'gb-lb--single';

  var stage = el('div', 'gb-lb__stage');
  var pic = el('img', 'gb-lb__img');
  pic.alt = '';
  pic.draggable = false;
  stage.appendChild(pic);

  var prev = el('button', 'gb-lb__nav gb-lb__nav--prev', '&#10094;');
  var next = el('button', 'gb-lb__nav gb-lb__nav--next', '&#10095;');
  var x = el('button', 'gb-lb__x', '&#10005;');
  prev.type = next.type = x.type = 'button';
  prev.setAttribute('aria-label', 'Previous image');
  next.setAttribute('aria-label', 'Next image');
  x.setAttribute('aria-label', 'Close');

  var info = el('div', 'gb-lb__info');
  var text = el('div', 'gb-lb__text');
  var titleEl = el('div', 'gb-lb__title');
  var statusEl = el('span', 'gb-lb__status');
  var descEl = el('div', 'gb-lb__desc');
  var countEl = el('div', 'gb-lb__count');
  text.appendChild(titleEl);
  text.appendChild(descEl);
  info.appendChild(text);
  info.appendChild(countEl);

  [stage, prev, next, x, info].forEach(function (n) { root.appendChild(n); });
  document.body.appendChild(root);

  var cur = 0, lastFocus = null;

  pic.addEventListener('load', function () {
    root.classList.remove('gb-lb--loading');
  });

  function show(i) {
    cur = (i + slides.length) % slides.length;
    var s = slides[cur];
    pic.style.transition = 'none';
    pic.style.transform = '';
    pic.style.opacity = '';
    requestAnimationFrame(function () { pic.style.transition = ''; });
    root.classList.add('gb-lb--loading');
    pic.src = s.src;
    titleEl.textContent = s.title;
    if (s.status) {
      statusEl.textContent = s.status;
      statusEl.className =
        'gb-lb__status' + (s.warn ? ' gb-lb__status--warn' : '');
      titleEl.appendChild(statusEl);
    }
    descEl.textContent = s.desc;
    descEl.hidden = !s.desc;
    countEl.textContent = (cur + 1) + ' / ' + slides.length;
    if (slides.length > 1) {
      new Image().src = slides[(cur + 1) % slides.length].src;
      new Image().src = slides[(cur - 1 + slides.length) % slides.length].src;
    }
  }

  function open(i) {
    lastFocus = document.activeElement;
    show(i);
    root.hidden = false;
    document.body.style.overflow = 'hidden';
    x.focus();
  }

  function close() {
    root.hidden = true;
    document.body.style.overflow = '';
    if (lastFocus && lastFocus.focus) lastFocus.focus();
  }

  slides.forEach(function (s, i) {
    s.el.style.cursor = 'zoom-in';
    s.el.addEventListener('click', function (e) {
      e.preventDefault();
      open(i);
    });
  });

  prev.addEventListener('click', function () { show(cur - 1); });
  next.addEventListener('click', function () { show(cur + 1); });
  x.addEventListener('click', close);

  document.addEventListener('keydown', function (e) {
    if (root.hidden) return;
    if (e.key === 'Escape') { e.preventDefault(); close(); }
    else if (e.key === 'ArrowRight') { e.preventDefault(); show(cur + 1); }
    else if (e.key === 'ArrowLeft') { e.preventDefault(); show(cur - 1); }
  });

  /* Swipe / drag to change slides; small tap on the backdrop closes. */
  var startX = 0, startY = 0, dragging = false, moved = false;
  stage.addEventListener('pointerdown', function (e) {
    dragging = true;
    moved = false;
    startX = e.clientX;
    startY = e.clientY;
    if (stage.setPointerCapture) stage.setPointerCapture(e.pointerId);
    pic.style.transition = 'none';
  });
  stage.addEventListener('pointermove', function (e) {
    if (!dragging || slides.length < 2) return;
    var dx = e.clientX - startX;
    if (Math.abs(dx) > 6 || Math.abs(e.clientY - startY) > 6) moved = true;
    pic.style.transform = 'translateX(' + dx + 'px)';
    pic.style.opacity = String(Math.max(0.35, 1 - Math.abs(dx) / 600));
  });
  function endDrag(e) {
    if (!dragging) return;
    dragging = false;
    var dx = e.clientX - startX;
    pic.style.transition = '';
    pic.style.opacity = '';
    if (slides.length > 1 && Math.abs(dx) > 60) show(dx < 0 ? cur + 1 : cur - 1);
    else pic.style.transform = '';
  }
  stage.addEventListener('pointerup', endDrag);
  stage.addEventListener('pointercancel', endDrag);
  stage.addEventListener('click', function (e) {
    if (moved) { moved = false; return; }
    if (e.target === stage) close();
  });
})();
